### PR TITLE
Adds identity option

### LINKED ISSUE #22: Add support for AzureAD Managed Identity for the GH Action pnp/action-cli-login
If the CLI supports managed identities, so should the GH action. More: https://discord.com/channels/1022486301536178246/1106617196211347516

### PR DESCRIPTION
**Pull request by milanholemans**
Closes #22 

In this PR:

- Adds new option `IDENTITY` to use auth with managed identity.
- Rewrote options list from the list to the table and added option type column
- Bumped version to `v2.3.0`

If I'm not mistaken I also have to rebuild the `dist` folder right? But `npm run build` doesn't do much.

### CODE REVIEW

**Comment by garrytrinder** [comment]
As discussed, let's change the approach to implement user-assigned managed identity, instead of system assigned.

**Review by garrytrinder — CHANGES_REQUESTED** [review]
As discussed, let's change the approach to implement user-assigned managed identity, instead of system assigned.

**Comment by milanholemans** [comment]
@garrytrinder thanks for the feedback, I processed it, and it's ready for another review.

**Comment by garrytrinder** [comment]
As per comments on the related issue, this requires more investigation into how we should handle federated identities.

**Pull request closed without merging**
